spring:
  main:
    web-application-type: servlet
#https://www.baeldung.com/spring-boot-h2-database
#  datasource:
#    url: jdbc:h2:file:./worter
#    driverClassName: org.h2.Driver
#    username: worter
#    password: worter
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect

#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  tcp:
#    enabled: true

  datasource:
    url: jdbc:mariadb://localhost:3306/worter
    username: worter
    password: worter
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate.ddl-auto: create-drop



  security:
    user:
      name: pippo
      password: pippo

server:
  port: 10001



